Vagrant.configure("2") do |config|
    config.vm.define "sample" do |nodeconfig|
        nodeconfig.vm.hostname = "sample"
        nodeconfig.vm.box = "bento/ubuntu-20.04"
        nodeconfig.vm.network :private_network, ip: "192.168.0.177"
    end
end

